name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: pnpm/action-setup@v2
          with:
            version: 7
        - uses: actions/setup-node@v3
          with:
            node-version: 18.x
            cache: "pnpm"

        - run: pnpm install --frozen-lockfile
        - run: pnpm run
